# Generated by Django 3.2.9 on 2022-10-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_remove_notice_nid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notices',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donetask',
            name='uid',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.IntegerField(default=''),
        ),
    ]
